# Generated by Django 4.2.2 on 2023-06-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'الفئة',
                'verbose_name_plural': 'الفئات',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الصورة')),
                ('image', models.ImageField(upload_to='images/', verbose_name='الصورة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'الصورة',
                'verbose_name_plural': 'الصور',
            },
        ),
    ]
