# Generated by Django 4.2.2 on 2023-06-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='type',
            field=models.CharField(choices=[('1', 'architecture'), ('2', 'advertising')], default=1, max_length=100, verbose_name='التصنيف'),
            preserve_default=False,
        ),
    ]
